import Head from "next/head";
import { Provider } from "react-redux";
import { useLoadScript } from "@react-google-maps/api";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./utils/theme";
import store from "./libs/store.js";
import Map from "./components/Map.js";

const libraries = ["places"];

export default function Home() {
  const { isLoaded, loadError } = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
    libraries,
  });

  if (loadError) return "Error loading maps";
  if (!isLoaded) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <ThemeProvider theme={theme}>
          <Map />
        </ThemeProvider>
      </Provider>
    </>
  );
}
